#! /bin/sh

# set wallpaper
setbg

killall -q sxhkd; sxhkd &
killall -q picom; sleep 0.3s; picom &
killall -q polybar; polybar main &
killall -q dunst; dunst &
killall -q unclutter; unclutter -idle 3 &
killall -q mpd; mpd &

# Keyboard speed
xset r rate 300 50 &	# Speed xrate up

# Xorg settings
xsetroot -cursor_name left_ptr &

pactl load-module module-bluetooth-discover &
pactl load-module module-bluetooth-policy &

xbacklight -set 50

xautolock -detectsleep -time 5 -locker slock &

xrdb $XDG_CONFIG_HOME/Xresources

remaps &


# We look for a non-laptop monitor to use for default, but use the laptop
# screen (LVDS) if there's nothing else. This is because I assume that if you
# have an extra screen attached to a laptop, you want to use that.
mainmonitor="$(bspc query --monitors --names | grep -v LVDS | head -n 1)"

# Start workspaces on the main monitor.
bspc monitor "$mainmonitor" -d 1 2 3 4 5 6 7 8 9 10


# BSPWM configuration
# -------------------
bspc config border_width								3
bspc config top_padding									40
bspc config bottom_padding							0
bspc config left_padding								0
bspc config right_padding								0
bspc config window_gap									12
bspc config click_to_focus							true
bspc config split_ratio									0.50

bspc config top_monocle_padding					17
bspc config single_monocle              false
bspc config borderless_monocle          true
bspc config gapless_monocle             true
bspc config focus_by_distance           true
bspc config focus_follows_pointer       true
bspc config history_aware_focus         true
bspc config pointer_modifier            mod4
bspc config pointer_action1             move
bspc config pointer_action2             resize_side
bspc config pointer_action3             resize_corner
bspc config remove_disabled_monitors    true
bspc config merge_overlapping_monitors  false

fwid=$(bspc query -N -n focused.automatic)
if [ -n "$fwid" ] ; then
    wattr wh $fwid | {
        read width height
        echo "split_dir=south"
        echo "split_ratio=0.5"
    }
fi


bspc config normal_border_color         "#14161F"
bspc config focused_border_color        "#14161F"
bspc config urgent_border_color         "#ffcb6b"
bspc config presel_feedback_color       "#c792ea"

bspc rule -a Zathura state=pseudo_tiled
